### PR TITLE
Fix typo to say Fork

### PR DESCRIPTION
**Pull request by jaredcwhite**
Saw a remaining place where it said Font Awesome…renamed that to Fork Awesome.

### CODE REVIEW

**Comment by tessus** [comment]
Thanks

**Comment by tessus** [comment]
I think we made a mistake. This should be changed in https://github.com/ForkAwesome/Fork-Awesome/tree/master/src/doc

Because it the web site is created from there...

**Comment by tessus** [comment]
the next time the web site is created your change will be overwritten. I can have a look at it later tonight.

**Comment by jaredcwhite** [comment]
Whoops, sorry about that. I should have figured the original source files would be located elsewhere.

**Comment by tessus** [comment]
No worries, I made the same mistake a while back.
-- 
regards Helmut K. C. Tessarek

(sent from a mobile device)

**Comment by xuv** [comment]
@all-contributors please add @jaredcwhite  for content

**Pull request merged**
