### PR TITLE
added a bunch, mentioned in https://github.com/ForkAwesome/Fork-Aweso…

### PR DESCRIPTION
**Pull request by diondresschers**
…me/pull/230#issuecomment-644255363

### CODE REVIEW

**Comment by diondresschers** [comment]
Hi @xuv , with this is should be easy to merge with the Master Branch.

I've added these icons/glyphs:

askfm				f33a;
blockstack			f33b;		
boardgamegeek		f33c;
bunny				f35f;		
buymeacoffee			f33d;		
cc-by				f33e;	
cc-cc				f33f;		
cc-nc-eu				f341;
cc-nc-jp				f342;
cc-nc				f340;		
cc-nd				f343;
cc-pd				f344;		
cc-remix				f345;	
cc-sa				f346;			
cc-share				f347;		
cc-zero				f348;		
conway-glider			f349;		
csharp				f34a;		
email-bulk-o			f34c;	
email-bulk			f34b;
gnu					f34d;		
google-play			f34e;
heroku				f34f;	
home-assistant		f350;	
java				        f351;			
mariadb				f352;	
markdown			f353;	
mysql				f354;			
nordcast				f355;	
plume				f356;			
postgresql			f357;		
sass-alt				f359;		
sass				f358;	
skate				f35a;			
sketchfab			f35b;		
tex					f35c;	
textpattern			f35d;		
unity				f35e;

Leaving out the earlier mentioned:

fa-rocket-o
weblate
speaker-deck
webmention
r-project
vuejs
duckduckgo
bunny-front
bunny-front-o
bunny-back
bunny-back-o

**Comment by xuv** [comment]
Thank you for this. IE'll take a look at it and let you know.

**Comment by xuv** [comment]
Ok, this has been merged into master. It'll be released in the next version. Once I have included two other pending PR we have. 
But thank you for creating this great PR. It was, as you said, really easy to merge.

**Comment by xuv** [comment]
@all-contributors please add @diondresschers  for design

**Comment by DougInAMug** [comment]
I'm confused... this has been merged into forkawesome for a while (v1.2) but that change hasn't propoagated to https://forkaweso.me which is stil on 1.1.7. Is that right?

**Comment by diondresschers** [comment]
> https://forkaweso.me which is stil on 1.1.7. Is that right?

There is indeed a mismatch between the versions of the GitHub repo, the website and the CDN.
I think they are not updated accordingly. 
I normally check on the amount of Icons/Fonts (not the version number), to determine the lagging of each.

https://github.com/ForkAwesome/Fork-Awesome/
https://forkaweso.me
https://www.jsdelivr.com/package/npm/fork-awesome

**Pull request closed without merging**
