### PR TITLE
Added boardgamegeek icon

### PR DESCRIPTION
**Pull request by diondresschers**
Hi, great fork! :1st_place_medal: I've added this due to: Icon Request: icon-boardgamegeek #228.

### CODE REVIEW

**Comment by diondresschers** [comment]
Icon request: Nordcast icon #227

**Comment by whoabuddy** [comment]
Thank you for including the Blockstack icon with this update! Much appreciated!!

**Comment by xuv** [comment]
Hello @diondresschers 

This is a very big PR. Do you mind if we break it down a little. There are a few things that I would definitely like to add to the set. But other icons that might need some more work. 

So far, as a general recommendation, I see that a bunch of icons with an "open design" don't really work well with the rest of the set. The contour lines are too thin compared to the contour lines being used in previous icons. Take a look at the `fa-rocket-o` you've included here and the [plus-square-o](https://forkaweso.me/Fork-Awesome/icon/plus-square-o/) we already have in the set.

I think it's worth-while redesigning the `fa-rocket-o` to be more in line with the rest.

As for the bunny series. I think it's a bit too much to include 4 of them. I would only keep one. I particularly like the simplicity in the design of the `fa-bunny-back`. I remove the others. And rename this one as `fa-bunny`.

Another thing that is difficult to balance, I also question myself al lot regarding this, is the relative sizer for the different brand icons. I like to keep sizes relatively similar between all of them. It's a difficult exercises as some brands have complicated designs and they don't read very well at small sizes. Some others have very bold shapes that seem to stick out more than others.  With that in mind, I think that `weblate`, `speaker-deck`, `webmention` and `r-project` could be reduced in size to fit better with the rest of the brand set. I'm hesitating for `vuejs`. It could also be a little smaller, if the thin line in the design doesn't disappear completely at small sizes.

Those are my suggestions. Let me know what you think. And if you need help to make those changes.

Thank you for your help.

Julien

**Comment by diondresschers** [comment]
Hi Julien, the PRs were made over several days, so I think at the end it looked like one BIG PR. Sure it's fine to break it down. I will work next days to resolve all individual issues. If there are questions I will let you know. I hope you have the time to resolve them. I think ForkAwesome is a beautiful project and I would hate to see it die...

**Comment by xuv** [comment]
It's my fault. I should have picked this up earlier. When you started the PR. Thank you for resolving the individual issues. I think I'll bump the minor version number with all this. I've been meaning to do this for a while. Just bumping the patch number has not been a good idea from the beginning.

I'm also leaning how to maintain an open source project. So I still make mistake. I agree with you. This project needs to stay alive. Let's go through this together see how we can have a smoother collaborative process afterwards.

**Comment by xuv** [comment]
hello @diondresschers 

Let me know how it goes. If it’s too much of a trouble to make all those changes at once, we can think of an alternative.

**Comment by diondresschers** [comment]
Hi @xuv 

It would be possible (and for me the easiest) to make one big commit

If you are okay with that, I will create 1 BIG commit, leaving out the:

fa-rocket-o
weblate
speaker-deck
webmention
r-project
vuejs
duckduckgo

and will rename fa-bunny-back to fa-bunny (and kill the other bunnies).

If you then can successfully merge my commit with Master Branch, that would be awesome. 

I can than start to redo the earlier mentioned icons in smaller PRs, one by one...

Let me know if that sounds okay with, so we can move on.

**Comment by xuv** [comment]
Sure. Let’s do that.

**Comment by diondresschers** [comment]
Okay @xuv 

I've deleted the Fork in my own GitHub Repo and created a brand new Fork so all possible conflicts are gone. Than I've copied all the required/wanted SVG icons from my own 'old' repo-backup to the new fresh Fork, and updated the icons.yml file.

I've created a single (big) pull request with all the new icons:
https://github.com/ForkAwesome/Fork-Awesome/pull/249

**Comment by xuv** [comment]
Closing this as most of it was merged in a later PR.

**Comment by antenore** [comment]
@xuv the commit https://github.com/ForkAwesome/Fork-Awesome/pull/230/commits/5fb6ecf87dd693014be657186fbe4d6e82f3232d hasn't been merged and I think that many other commits were not included.

My main burden is about the weblate icon, I miss it really hard. See #218  but I think others have the same issue?

Can you kindly cherry-pick the above commit ?

Thanks in advance!!!

**Pull request closed without merging**
