### PR TITLE
Add Tor Project logo icons (fixes #144)

### LINKED ISSUE #144: Icon request: fa-torproject
## Icon

https://www.torproject.org/images/onion.jpg
https://www.torproject.org/docs/trademark-faq.html.en

## Name Suggestion

`torproject` or `tor`

## Use Case

https://www.torproject.org

### PR DESCRIPTION
**Pull request by lucaspetter**
Onion logo icons from the Tor Project's [brand styleguide](https://styleguide.torproject.org/visuals/#assets) and [brand asset repo](https://github.com/TheTorProject/tor-media), licenced under CC-BY 3.0.
- `tor-onion`
- `tor-onion-circle`

Complied files not included in PR.

See discussion at #144.

### CODE REVIEW

**Comment by xuv** [comment]
@lucaspetter Thanks for submitting those.
I really find the `tor-onion` one to be a great addition to the set.

But I don't think the `tor-onion-circle` is necessary.
The brand guidelines don't have a tor onion in a circle anywhere. And the design in a circle that we have in the fork awesome set don't look like that. Also, we mostly have brand icons in a square than in a circle.


So, if you could remove that `tor-onion-circle` and resubmit your PR. I'll be happy to merge it.

**Comment by lucaspetter** [comment]
@xuv Okay, the `tor-onion-circle` icon has been removed.

**Comment by xuv** [comment]
@lucaspetter Thanks for the changes.

**Comment by wioxjk** [comment]
When will this be accessible?

**Pull request merged**
