### PR TITLE
Add JavaScript Icon

### LINKED ISSUE #46: Icon request: fa-javascript
Hi :hand: 

There is not really an official logo for javascript, I found two different types of logos.

Files (1x .ai and 1x .svg): 
[javascript.zip](https://github.com/ForkAwesome/Fork-Awesome/files/1778132/javascript.zip)
 

Preview : 
preview-logo-javascript

Preview

### PR DESCRIPTION
**Pull request by mrdrogdrog**
This PR adds the JavaScript Icon

Fixes #46

### CODE REVIEW

**Review by shinenelson — CHANGES_REQUESTED** [review]
the icon looks good.

image

but you will have to rebase the base branch with the head branch to resolve the merge conflict.

**Comment by mrdrogdrog** [comment]
done

**Review by shinenelson — APPROVED** [review]

**Comment by KaKi87** [comment]
Hello,
I can't find this icon ?
Thanks

**Comment by mrdrogdrog** [comment]
It's merged but probably hasn't been released yet.

**Comment by KaKi87** [comment]
Really ? But it's been almost a year and a half

**Comment by mrdrogdrog** [comment]
Last release was on Aug 26, 2021.

**Comment by mrdrogdrog** [comment]
Not sure if this project is still alive. I'm switching to bootstrap icons with one project that uses this before. 🤷

**Comment by KaKi87** [comment]
Well, thanks to [Useful Forks](https://useful-forks.github.io/), I found out that @MSKNET made a [recent build](https://github.com/MSKNET/Fork-Fork-Awesome/blob/master/css/fork-awesome.min.css), and thanks to [GitHack](https://raw.githack.com/), I'm able to use `fa-javascript` on my app using the following import : https://rawcdn.githack.com/MSKNET/Fork-Fork-Awesome/d4e848e3f69322233482cdd40ab657087e177fbd/css/fork-awesome.min.css

**Pull request merged**
