### PR TITLE
Create ringing bell (Fix #197)

### LINKED ISSUE #197: Youtube style ringing bell
## Name Suggestion

ringing bell?

## Use Case

Useful for identifying that you're subscribed for notifications to something

### PR DESCRIPTION
**Pull request by qwazix**
This is how it looks like

image

### CODE REVIEW

**Comment by xuv** [comment]
This looks great. Let me check it out.

**Comment by xuv** [comment]
Hey. Thank you for your submission. It's almost ready to be merged.
To finish it, could you add an entry for the icon in the file `src/icons/icons.yml`.

Here is the entry for the bell symbol to get inspired:
```
  - name:       Bell
    id:         bell
    unicode:    f0a2
    created:    0.4
    filter:
      - alert
      - reminder
      - notification
    categories:
      - Web Application Icons
```

You will have to change the 4 first properties of this to correspond to your entry. The rest seems pretty similar. (So you know, the unicode point has been assigned by the fontcustom creation tool.)

Let me know if you have any questions.

**Comment by qwazix** [comment]
Done, also added the outlined version

**Comment by xuv** [comment]
Great. Perfect.

@all-contributors please add @qwazix  for design

**Pull request merged**
