### PR TITLE
Add freedesktop.org logo

### PR DESCRIPTION
**Pull request by elboulangero**
Freedesktop is a community "focused on interoperability and shared technology for open-source graphical and desktop systems". They host a number of major FOSS projects on their GitLab, for example GStreamer, Wayland, Xorg, Mesa and many more.

- https://www.freedesktop.org/
- https://gitlab.freedesktop.org

NOTE: if applicable, please merge this request after #258 (this MR contains both commits, because of the `icons.yaml` and the unicode value in it.

### CODE REVIEW

**Comment by tclavier** [comment]
@tessus I thinks, you can merge this PR.

**Comment by tessus** [comment]
Do we know, if wee can add those icons without being sued? If yes, I'll merge.

Some projects, even open source projects, are very restrictive when it comes to their brand icons.

**Comment by elboulangero** [comment]
For the freedesktop icon, we can ask Daniel Stone what he thinks about it. He's quite [involved with freedesktop](https://www.fooishbar.org/blog/gitlab-fdo-introduction/), and I also had the chance to meet him in person, so let's ask.

@fooishbar : [Fork Awesome](https://forkaweso.me/) is a CSS font that provides ~ 750 icons. In this PR I proposed to add the freedesktop font. Do you think it's OK from a legal point of view?

The license for the font is described here: https://github.com/ForkAwesome/Fork-Awesome#license

**Comment by elboulangero** [comment]
@tessus As for the GNOME logo, GNOME has this page: https://www.gnome.org/logo-and-trademarks/. Maybe a written permission is required. I just sent an email to them, and asked if they could comment on this PR.

**Comment by fooishbar** [comment]
We have no issues from a legal sense as there are no trademarks in play (unlike GNOME). The logo itself can be assumed to be licensed under MIT, so I see no issues with this derivative. Please refer to us as `freedesktop.org` (lowercase 'f', suffix '.org') where practical though - e.g. `fa-freedesktop` is a totally fine contraction for the asset ID, but any display text should be 'freedesktop.org' and not 'Freedesktop'. Thanks!

**Comment by elboulangero** [comment]
> Please refer to us as freedesktop.org

Just updated the PR to change the icon name from `Freedesktop` to `freedesktop.org`. Thanks @fooishbar for the quick feedback!

**Comment by elboulangero** [comment]
@tessus I just updated the PR so that it includes only the freedesktop.org icon (initially it contained both GNOME and freedesktop.org icons). So I think it's good to be merged now.

I will open another PR for the GNOME icon alone.

Thanks!

**Review by shinenelson — COMMENTED** [review]
I tried building this icon.

While it looks well in sizes > 32 px, it _looks_ burred in smaller sizes because of the border outline of the logo.

image

Is it possible to drop the border outline for the icon? Would it be against the brand guidelines? I could not find any documentation for the brand guidelines for freedesktop. Could someone check or point in the right direction?

**Comment by fooishbar** [comment]
No objections from a brand PoV, no.

**Comment by shinenelson** [comment]
@elboulangero, would you have the time to update the icon without the border outline so that it looks better on smaller sizes?

**Comment by elboulangero** [comment]
@shinenelson Heya, I updated the icon, and also rebased the branch on master. Thanks for the headup!

**Review by shinenelson — APPROVED** [review]
It looks a lot better now :+1:

image

**Comment by shinenelson** [comment]
@all-contributors please add @elboulangero for infra, doc and design

**Pull request merged**
