### PR TITLE
Fix - dev-to icon missing from scss

### PR DESCRIPTION
**Pull request by eidsonator**
Adds a `$fa-var-dev-to` variable in _variables.scss and and selector in _icons.scss so the  *-dev-to icon is available when compiling from sass.

Addresses #168

### CODE REVIEW

**Comment by xuv** [comment]
@eidsonator Thanks for pointing this out, opening the issue and proposing a fix. Really appreciated.

Now, since these files are automatically generated by the build script, I'm curious to find out where the error comes from. There is probably an error in the way these files were built and thus changing them here unfortunately won't fix it.

I think the problem comes from the fact that theses particular .scss files have not been updated since a while. Probably since version 1.0.11 if I believe `_variables.scss` https://github.com/ForkAwesome/Fork-Awesome/blob/c14e361ccb9d5a266e523e04d8626cf828343d59/scss/_variables.scss#L9

This will require to fix the build script (which is a hack around Jekyll).
Do you know Jekyll? Do you feel it's something you'd like to tackle?

**Comment by eidsonator** [comment]
It's been a few years since I've touched Jekyll, but let me see if I can brush off the cobwebs and see what I can come up with.

**Comment by xuv** [comment]
If that is any help, Jekyll handles sass files automatically.
Unfortunately, that's a behavior we don't want.
What we want is for Jekyll to consider the sass source files as text template, not as sass files.
That's why [fork-awesome.scss.txt](https://github.com/ForkAwesome/Fork-Awesome/blob/master/src/doc/assets/fork-awesome/scss/fork-awesome.scss.txt) is written like this. 

And I now realize that `icons.scss` and `variables.scss` in the same folder need probably to follow the same pattern.

**Comment by eidsonator** [comment]
It looks like Jekyll is ignoring all of the underscore files in src/doc/assets/fork-awesome/scss when copying to _site, even if the file has a .txt extension.

It looks like removing the underscore in the assets file and then pre-pending it on the mv in the Makefile mv statement fixes everything.

mv ${FA_SCSS_DIRECTORY}/variables.scss.txt ${FA_SCSS_DIRECTORY}/_variables.scss

So, I could rename all the underscrore files in the scss directory and add a mv command for each file.  

Also, I don't think the following command is having the desired behaviour in my environment. 
https://github.com/ForkAwesome/Fork-Awesome/blob/c14e361ccb9d5a266e523e04d8626cf828343d59/src/doc/Makefile#L39

I'm guessing it is supposed to copy the subdirectories to the root of the project.  It is copying the parent directory recursively to the project root.  

So I get:
- root
  - fork-awesome
    - css
    - less
    - scss

Instead of"
- root
  - css
  - less
  - scss

Changing that line to:

``' bash
cp -r ${FA_ROOT_DIRECTORY}/* ../
```

With the asterisk fixes that behaviour.  I can make that change, too, unless I am misunderstanding the desired behaviour.

**Comment by xuv** [comment]
Go ahead. Rename all the files you need. The pattern you are proposing sounds good.

**Comment by xuv** [comment]
Hey. Thanks for these changes.

As you have encountered, the `package-lock.json` got changed. It happens when people install it. Maybe we should not have that file in the repo in the first place. But, if you don't mind reverting your commit on this one. That would be good, so we keep the package-lock as it is.

The second thing I see is that there is a `less/font-awesome.less` file that seems to be removed in one of your commits. And that's probably not a good thing. I have not really seen why it was removed. Can you double check that.

For the rest, it seems all good.

Thanks for this.

**Comment by eidsonator** [comment]
I had already reverted the package-lock.json file, in the following commit.  I thought that that the package-lock file was only changed when an `npm update` was run, not an `npm install`.  So I am a little confused by that.

Regarding the less/font-awesome.less I deleted the entire root/less directory to ensure that it was properly created on a build, which is how that file disappeared.  It is not a build artifact apparently.  I have reverted that change as well.  The deletion was unintentional, however, it does look like that that file is not used any where.  It could be a breaking change if someone is importing that instead of the fork-awesome.less file though.

**Comment by xuv** [comment]
Oh, my bad. You are totally right. I'm not even realizing what I'm writing. I'm confusing my self with names. Fork or Font awesome. Geez. 🤣  You totally had the better approach to clear the build folder all together to test your changes. My bad. 

So sorry for the back and forth. 

And you are right about package-lock. It's more confusing than not. We should just remove it.

**Comment by eidsonator** [comment]
Apparently the package-lock.json can be updated by an `install`, which sort of defeats the whole purpose of a lock file.  This is detailed in this  [stackoverflow answer].  There is a `npm ci` command which doesn't update the lock file.  I've tested this, it works.  I wasn't familiar with this behaviour because I use yarn for my package management, which isn't this backwards.  So we could remove the package-lock file or change all instances of `npm install` to `npm ci` in the documentation and in any scripts.

Regarding the less/font-awesome.less file, Would you like it removed?  Would it be best to have a 'clean' step in the build process that removes the less and scss files before a build?  I think that would have caught the original bug that this pull request addresses, you would have wondered why ~10 .scss files were being removed in the pull request.


[stackoverflow answer]: https://stackoverflow.com/a/45566871/2249502

**Comment by xuv** [comment]
Adding `npm ci` to the documentation sounds good. We had one time a case of a npm package version being different on 2 systems and it took us a while to figure out where those errors where coming from. 

If you do change the doc, the source of the README file is in the `src/doc/README.md-nobuild` file. I know, it's kind of weird, but the README file is also the result of the build.

As for a cleaning script before a build, that sounds pretty good indeed. Totally agree with you it would help us catch those bugs earlier.

**Comment by eidsonator** [comment]
I'll look into that failure - the npm version on the travis.ci doesn't support the `ci` command - I can change it back to `install` for the travis script or look at bumping the npm version in travis.

**Comment by xuv** [comment]
@eidsonator Yeah, I think you can bump the npm version on Travis. Sounds good to me.

**Comment by eidsonator** [comment]
I just changed the `npm ci` back to `npm install` for the travis.yml file.  It looks like changing the npm version requires updating the package-lock.json file, which is what we were trying to avoid doing in the first place.  The only benefit that running `ci` command would get us on travis is the check running a couple seconds faster.  The npm version on travis doesn't alter the lock file.

I think this should be ready to pull, if you don't see any other problems with it.

**Comment by xuv** [comment]
Awesome. Thanks so much for all this work, @eidsonator 
If you have more ideas to improve our build process, documentation or anything that you feel needs polishing, please, don't hesitate to do so.
Since this is fixing quite a big bug, I'm going to release a new version soon.

In the meantime, @allcontributors[bot] please add @eidsonator for code and bug

**Pull request merged**
