### PR TITLE
Add Lemmy Icon

### LINKED ISSUE #289: Logo for Lemmy (reddit like service for the fediverse)
## Icon

image
just copied the logo from the website but I am sure there is an svg somewhere
you can see the logo in use here https://lemmy.ml/post/59433

Lemmy is a pretty popular fediverse project. I came to file this issue because a project that I use, uses ForkAwesome for their fediverse logos and needs this logo to continue, here is the issue on their side: https://gitlab.com/mugcake/share-freedom-extension/-/issues/2

### PR DESCRIPTION
**Pull request by mrdrogdrog**
This PR adds the Icon of [Lemmy](https://join-lemmy.org/)

Fixes #289

### CODE REVIEW

**Review by shinenelson — CHANGES_REQUESTED** [review]
this looks too faint in sizes smaller than 36px especially since it is an outline logo and not filled.

image

could it be possible to increase the stroke width of the lines so that it becomes more legible on smaller sizes?

**Comment by mrdrogdrog** [comment]
Try again

**Comment by shinenelson** [comment]
It is better but still not great. You could compare with `lemon-o` that is right below `lemmy` in the `forkawesome-preview.html` page.

image

**Comment by mrdrogdrog** [comment]
Rebased and corrected

**Review by shinenelson — APPROVED** [review]
now it looks a lot more legible :+1:

image

**Comment by wakest** [comment]
hell yeah thank you all for making this happen! this was the one I filed that lead to a lot of discussion!

**Pull request merged**
