### PR TITLE
Add Mumble Icon

### LINKED ISSUE #278: Icon Request: fa-mumble
### Name Suggestion
Mumble

### Use Case
Mumble is an Open Source, low-latency and high-quality voice-chat program written on top of Qt and Opus. 
We want to link to a Mumble instance and use an icon for that.

### PR DESCRIPTION
**Pull request by mrdrogdrog**
This PR adds the icon of [Mumble](https://mumble.info)

Fixes #278

### CODE REVIEW

**Comment by shinenelson** [comment]
I will let you fix that merge conflict while I build the icon locally to see how it looks.

PS : You cannot fix your own pull request, I think you intended to link #278.

But good going anyway :+1:

**Comment by mrdrogdrog** [comment]
Fixed it. I also resized the icon. You should pull again.

**Review by shinenelson — COMMENTED** [review]
while this looks okay

image

I think we could avoid the circle around the logo unless there are strict brand guidelines around it.

**Comment by mrdrogdrog** [comment]
I'm not sure.. It's always used with that circle.

**Comment by shinenelson** [comment]
From a brand perspective, sure, but I am thinking about the various use-cases where this icon might be used. It can be used on project pages where they list their social media accounts. And when all other icons do not have an enclosure, it would be odd if this logo is used with the enclosure.

And besides, one can [stack](https://forkaweso.me/Fork-Awesome/examples/#stacked) a `fa-circle`, `fa-square` or whatever other icon that is available in the set to re-create their desired output with fork-awesome.

**Comment by mrdrogdrog** [comment]
I removed the circle

**Review by shinenelson — APPROVED** [review]
this looks much better

image

**Pull request merged**
