### PR TITLE
Add Discord icon

### PR DESCRIPTION
**Pull request by micahilbery**

### CODE REVIEW

**Comment by xuv** [comment]
@micahilbery This is great, thank you.

But somehow, a bug happened and i'm not really sure why. The font generated and copied in the `fonts` & `src/doc/assets` folder have a bug in them. They do not show properly.

screen shot 2018-02-21 at 11 25 14

(See liberapay-square for example, but a lot of others too)
Do you know why this might have happened?

**Comment by micahilbery** [comment]
I'm not sure. However whenever I ran `make` it said I modified every SVG added in v1.0 I just didn't add them in my commit. So maybe whatever is happening there during the make is messing with the other icons.

**Comment by xuv** [comment]
Hmm. This is strange. We need to investigate this. It's probably not a good idea to re-run the SVG optimizer script on every file at every build. I should remove that from the build script.
We should probably only run this on new added icons. Or ask people who submit new icons to clean up their files before submitting.

Can you try rerunning `make` without that `svgo` line and then commit the resulting font. 

We'll see later for a solution to this problem.

**Comment by micahilbery** [comment]
I re-wrote over the font files with the ones from master that way I knew it was starting fresh. I commented out the svgo line in the makefile and rebuilt the font. I just pushed the resulting font changes.

**Comment by xuv** [comment]
Hmmm. Weird. I still have the same error. It still shows a lot of icons are distorted. 
By any chance, would you have FontForge installed? 
Could you check the glyphs on your side in the generated font (check the webfont.svg) file for example.

I'm starting to wonder if it's on my system that this happen or if it's something that happens in yours too?

**Comment by micahilbery** [comment]
It's happening to me too :confused: 

screenshot from 2018-02-21 11 49 30

**Comment by xuv** [comment]
When I generated the font myself, based on the svg file set of this branch, I get some differences in the webfont setting which I do not understand.

screen shot 2018-02-21 at 12 56 06

I hope I'm not bothering you with this. I would really like to get to the bottom of this. Of course, I could just generate the font on my system and the merge this pull request. But I feel that if we find the root cause of this, we will be better off in the future.

**Comment by xuv** [comment]
Oh, my version of FontForge is more recent that yours. Would that be the reason? Could you please be sure you have the latest one? Mine seems to be 20170925 and yours is 20170731

**Comment by micahilbery** [comment]
You're not bothering me at all. I want to figure this out and am just as curious as you. I found a the fontforge ppa and updated to 20**17**0731 witch is the highest that I think I can get to on elementary OS (or any ubuntu or debian based distro). I will try with this version and see what happens.

**Comment by micahilbery** [comment]
I think that did it. I think it was my disgustingly old version of fontforge. I just pushed up the changes. Take a look and see if that fixed it for you.

**Comment by xuv** [comment]
Yes. Awesome. 
I added the generated CSS, etc. 
Will now merge.

**Comment by micahilbery** [comment]
:tada: :confetti_ball:  :tada:

**Pull request merged**
